version: '3.1'

services:
  mysql:
      image: mysql:8.0.28
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: labsql
        MYSQL_DATABASE: labs
        MYSQL_USER: usr_labs
        MYSQL_PASSWORD: labsql
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
